// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCea6eQtsP4VRzqK5gGjBfcqckXkoFSWvE',
    appId: '1:108515575494:web:4433c1781e9eb76ed5f9c7',
    messagingSenderId: '108515575494',
    projectId: 'authur-4c694',
    authDomain: 'authur-4c694.firebaseapp.com',
    storageBucket: 'authur-4c694.appspot.com',
    measurementId: 'G-DZGFM5HNF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ8b3p3NmUPwYce0cefujk8CZ0k-2345s',
    appId: '1:108515575494:android:e50ebfdd4d7ecc50d5f9c7',
    messagingSenderId: '108515575494',
    projectId: 'authur-4c694',
    storageBucket: 'authur-4c694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQfx570ixB-sgUYDnrF9PTWWtIdOjcIg',
    appId: '1:108515575494:ios:0832d13dc1d3575cd5f9c7',
    messagingSenderId: '108515575494',
    projectId: 'authur-4c694',
    storageBucket: 'authur-4c694.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQfx570ixB-sgUYDnrF9PTWWtIdOjcIg',
    appId: '1:108515575494:ios:238e23d702286ee1d5f9c7',
    messagingSenderId: '108515575494',
    projectId: 'authur-4c694',
    storageBucket: 'authur-4c694.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
